name: Buyable_Warps
version: 1.5
description: "A Deca addon plugin that allows players to buy warps and teleport to them."
api-version: 1.20
author: Noobasauras_Rex
noteable credits: Sarinsa, Random6894, Monster_What
main: com.playdeca.BuyableWarps
depend: ["Vault"]

commands:
  buywarp:
    description: "Allows a player to buy a set of co-ordinates to warp to"
    usage: "/buywarp"
    aliases: ["bw"]